### ISSUE TITLE
#TODO

### ISSUE THREAD

**Issue by lixiaochuan2020** [JimmyyyChen/modeleval#40]
- [x] 部署 @lixiaochuan2020 🥇 
- [x] 测试 @molamola-msc m 🥇
- [x] 整理会议纪要文档 @lixiaochuan2020 🥉 
- [x] 主观 + 对抗性前后端API调通 @lixiaochuan2020 @JimmyyyChen 🥇
- [x] 规定所有静态标签 @lixiaochuan2020 🥉 
- [x] #53
- [x] 数据集内部操作，包括增删改查、整体上传数据集 @ZhangZhiyuan-2021 @molamola-msc  🥇 
- [x] 添加一个非常大的数据集，压力测试 @ZhangZhiyuan-2021 @molamola-msc 🥉 
- [x] #49
- [x] PPT及讲稿，讲解流程设计 @JimmyyyChen @lixiaochuan2020 @ZhangZhiyuan-2021 @molamola-msc  🥈 
- [x] 数据集、模型、用户评论区 @JimmyyyChen @ZhangZhiyuan-2021  🥇 
- [x] 当上传的数据集错误或事测试无法运行时返回错误给前端 🥉

**Comment by JimmyyyChen** [comment]
Done!
